/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import App.AdminApp;
import App.checkInfo;
import Object.Admin;
import Object.Lecturer;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class AdminQLAD extends javax.swing.JFrame {

    /**
     * Creates new form QLSV
     */
    AdminApp adminApp = new AdminApp();
    ArrayList<Admin> listAD = adminApp.loadFile();
    checkInfo checkData = new checkInfo();

    public AdminQLAD() {
        initComponents();
        showAdminList(listAD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textBirthday = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textPassword = new javax.swing.JTextField();
        btnEditAD = new javax.swing.JButton();
        btnDeleteAD = new javax.swing.JButton();
        btnExitQLSV = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_AD = new javax.swing.JTable();
        searchAD = new javax.swing.JButton();
        btnAddAD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý giảng viên");

        jPanel3.setBackground(new java.awt.Color(53, 53, 242));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Mã số AD");

        textId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textIdKeyPressed(evt);
            }
        });

        jLabel2.setText("Họ và tên");

        jLabel3.setText("Ngày sinh");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Địa chỉ email");

        jLabel7.setText("Số điện thoại");

        jLabel12.setText("Mật khẩu");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textAddress)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textId))
                    .addComponent(textName)
                    .addComponent(textEmail)
                    .addComponent(textPhone)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(0, 113, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(4, 4, 4)
                .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        btnEditAD.setBackground(new java.awt.Color(35, 35, 253));
        btnEditAD.setText("Sửa");
        btnEditAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditADActionPerformed(evt);
            }
        });

        btnDeleteAD.setBackground(new java.awt.Color(35, 35, 253));
        btnDeleteAD.setText("Xóa");
        btnDeleteAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteADActionPerformed(evt);
            }
        });

        btnExitQLSV.setBackground(new java.awt.Color(35, 35, 253));
        btnExitQLSV.setText("Thoát");
        btnExitQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitQLSVActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH QUẢN TRỊ VIÊN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N

        table_AD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Mật khẩu", "Họ tên", "Ngày sinh", "Địa chỉ", "Email", "SĐT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_AD.setColumnSelectionAllowed(true);
        table_AD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ADMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_AD);
        table_AD.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        searchAD.setBackground(new java.awt.Color(35, 35, 253));
        searchAD.setText("Tìm kiếm");
        searchAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchADActionPerformed(evt);
            }
        });

        btnAddAD.setBackground(new java.awt.Color(35, 35, 253));
        btnAddAD.setText("Thêm");
        btnAddAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddADActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(searchAD)
                                .addGap(361, 361, 361)
                                .addComponent(btnAddAD)
                                .addGap(38, 38, 38)
                                .addComponent(btnEditAD)
                                .addGap(42, 42, 42)
                                .addComponent(btnDeleteAD)
                                .addGap(35, 35, 35)
                                .addComponent(btnExitQLSV)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddAD)
                            .addComponent(btnEditAD)
                            .addComponent(btnDeleteAD)
                            .addComponent(btnExitQLSV))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchAD)
                        .addGap(24, 24, 24))))
        );

        btnEditAD.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //search theo id, mail
    private void searchADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchADActionPerformed
//        SearchStudent ADsearch = new SearchStudent();
//        ADsearch.setVisible(true);
    }//GEN-LAST:event_searchADActionPerformed

    //click button Exit
    private void btnExitQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitQLSVActionPerformed
        AdminPage ad = new AdminPage();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitQLSVActionPerformed

    //click button delete > delete data in table and file
    private void btnDeleteADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteADActionPerformed
        // TODO add your handling code here:
        int i = table_AD.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) table_AD.getModel();
        if (i >= 0) {
            //delete data in table
            String idDel = tableModel.getValueAt(i, 0).toString();
            tableModel.removeRow(i);
            //delete data in arraylist
            for (int j = 0; j < listAD.size(); j++) {
                if (listAD.get(i).getId().equals(idDel)) {
                    listAD.remove(i);
                    JOptionPane.showMessageDialog(null, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    adminApp.saveFile(listAD);
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnDeleteADActionPerformed

    //click button Edit > update data in table and file
    private void btnEditADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditADActionPerformed

        try {
            DefaultTableModel tableModel = (DefaultTableModel) table_AD.getModel();

            int i = table_AD.getSelectedRow();
            //edit table
            tableModel.setValueAt(textId.getText(), i, 0);
            tableModel.setValueAt(textPassword.getText(), i, 1);
            tableModel.setValueAt(textName.getText(), i, 2);
            tableModel.setValueAt(textBirthday.getText(), i, 3);
            tableModel.setValueAt(textAddress.getText(), i, 4);
            tableModel.setValueAt(textEmail.getText(), i, 5);
            tableModel.setValueAt(textPhone.getText(), i, 6);

            //edit arraylist
            listAD.get(i).setId(textId.getText());
            listAD.get(i).setPassword(textPassword.getText());
            listAD.get(i).setName(textName.getText());
            listAD.get(i).setBirthday(textBirthday.getText());
            listAD.get(i).setAddress(textAddress.getText());
            listAD.get(i).setEmail(textEmail.getText());
            listAD.get(i).setPhone(textPhone.getText());
            adminApp.saveFile(listAD);
            JOptionPane.showMessageDialog(null, "Thao tác thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Thao tác không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEditADActionPerformed

    //when click to a row, the row's detail info display in Detail Info in the left
    private void table_ADMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ADMouseClicked
        // TODO add your handling code here:
        int index = table_AD.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) table_AD.getModel();
        textId.setText(tableModel.getValueAt(index, 0).toString());
        textPassword.setText(tableModel.getValueAt(index, 1).toString());
        textName.setText(tableModel.getValueAt(index, 2).toString());
        textBirthday.setText(tableModel.getValueAt(index, 3).toString());
        textAddress.setText(tableModel.getValueAt(index, 4).toString());
        textEmail.setText(tableModel.getValueAt(index, 5).toString());
        textPhone.setText(tableModel.getValueAt(index, 6).toString());
    }//GEN-LAST:event_table_ADMouseClicked

    //click button add a student
    private void btnAddADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddADActionPerformed

        if (adminApp.searchAD(textId.getText(), textEmail.getText()) == -3 || adminApp.searchAD(textId.getText(), textEmail.getText()) == -1) {

            //add to arrayList
            Admin ad = new Admin();
            ad.setId(textId.getText());
            ad.setPassword(textPassword.getText());
            ad.setAddress(textAddress.getText());
            if (textName.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tên không được để trống", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                ad.setName(textName.getText());
                if (checkData.checkBirthday(textBirthday.getText())) {
                    ad.setBirthday(textBirthday.getText());
                    if (checkData.checkEmail(textEmail.getText())) {
                        ad.setEmail(textEmail.getText());
                        if (checkData.checkPhone(textPhone.getText())) {
                            ad.setPhone(textPhone.getText());
                            listAD.add(ad);
                            adminApp.saveFile(listAD);
                            //add student's info to table 
                            DefaultTableModel tableModel = (DefaultTableModel) table_AD.getModel();
                            tableModel.addRow(new Object[]{textId.getText(), textPassword.getText(), textName.getText(),
                                textBirthday.getText(), textAddress.getText(), textEmail.getText(), textPhone.getText()});
                            JOptionPane.showMessageDialog(null, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "ID or email not available", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnAddADActionPerformed

    private void textIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIdKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_textIdKeyPressed

    //load data from arrayList to table
    private void showAdminList(ArrayList<Admin> listAD) {
        DefaultTableModel model = (DefaultTableModel) table_AD.getModel();
        Object[] row;
        for (int i = 0; i < listAD.size(); i++) {
            row = new Object[7];
            row[0] = listAD.get(i).getId();
            row[1] = listAD.get(i).getPassword();
            row[2] = listAD.get(i).getName();
            row[3] = listAD.get(i).getBirthday();
            row[4] = listAD.get(i).getAddress();
            row[5] = listAD.get(i).getEmail();
            row[6] = listAD.get(i).getPhone();
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminQLAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminQLAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminQLAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminQLAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminQLAD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAD;
    private javax.swing.JButton btnDeleteAD;
    private javax.swing.JButton btnEditAD;
    private javax.swing.JButton btnExitQLSV;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchAD;
    private javax.swing.JTable table_AD;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textBirthday;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textPassword;
    private javax.swing.JTextField textPhone;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Admin> loadFile() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
