/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import App.LecturerApp;
import App.checkInfo;
import Object.Lecturer;
import java.awt.HeadlessException;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class AdminQLGV extends javax.swing.JFrame {

    /**
     * Creates new form QLSV
     */
    LecturerApp lecturerApp = new LecturerApp();
    ArrayList<Lecturer> listLecturer = lecturerApp.loadFile();
    checkInfo checkData = new checkInfo();

    public AdminQLGV() {
        initComponents();
        showLecturerList(listLecturer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textBirthday = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textPhone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textPassword = new javax.swing.JTextField();
        selectSchool = new javax.swing.JComboBox<>();
        textLiteracy = new javax.swing.JTextField();
        btnEditQLGV = new javax.swing.JButton();
        btnDeleteGV = new javax.swing.JButton();
        btnExitQLSV = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_GV = new javax.swing.JTable();
        searchGV = new javax.swing.JButton();
        btnAddGV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý giảng viên");

        jPanel3.setBackground(new java.awt.Color(53, 53, 242));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Mã số GV");

        textId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textIdKeyPressed(evt);
            }
        });

        jLabel2.setText("Họ và tên");

        jLabel3.setText("Ngày sinh");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Địa chỉ email");

        jLabel7.setText("Số điện thoại");

        jLabel8.setText("Viện đào tạo ");

        jLabel9.setText("Trình độ");

        jLabel12.setText("Mật khẩu");

        selectSchool.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Viện Công nghệ thông tin và truyền thông", "Viện Dệt may", "Viện Cơ khí", "Viện Vật lý kĩ thuật", "Viện Điện", "Viện Điện tử Viễn thông", "Viện Ngoại Ngữ", "Viện Đào tạo Quốc tế", "Viện Kinh kế và quản lý" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectSchool, 0, 0, Short.MAX_VALUE)
                    .addComponent(textPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textAddress)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textId))
                    .addComponent(textName)
                    .addComponent(textEmail)
                    .addComponent(textPhone)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textLiteracy))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(4, 4, 4)
                .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(selectSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLiteracy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        btnEditQLGV.setBackground(new java.awt.Color(35, 35, 253));
        btnEditQLGV.setText("Sửa");
        btnEditQLGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditQLGVActionPerformed(evt);
            }
        });

        btnDeleteGV.setBackground(new java.awt.Color(35, 35, 253));
        btnDeleteGV.setText("Xóa");
        btnDeleteGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGVActionPerformed(evt);
            }
        });

        btnExitQLSV.setBackground(new java.awt.Color(35, 35, 253));
        btnExitQLSV.setText("Thoát");
        btnExitQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitQLSVActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH GIẢNG VIÊN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N

        table_GV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Mật khẩu", "Họ tên", "Ngày sinh", "Địa chỉ", "Email", "SĐT", "Trình độ", "Viện/Khoa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_GV.setColumnSelectionAllowed(true);
        table_GV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_GVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_GV);
        table_GV.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
        );

        searchGV.setBackground(new java.awt.Color(35, 35, 253));
        searchGV.setText("Tìm kiếm");
        searchGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGVActionPerformed(evt);
            }
        });

        btnAddGV.setBackground(new java.awt.Color(35, 35, 253));
        btnAddGV.setText("Thêm");
        btnAddGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(searchGV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddGV)
                .addGap(31, 31, 31)
                .addComponent(btnEditQLGV)
                .addGap(40, 40, 40)
                .addComponent(btnDeleteGV)
                .addGap(44, 44, 44)
                .addComponent(btnExitQLSV)
                .addGap(283, 283, 283))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(636, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditQLGV)
                    .addComponent(btnDeleteGV)
                    .addComponent(btnExitQLSV)
                    .addComponent(searchGV)
                    .addComponent(btnAddGV)))
        );

        btnEditQLGV.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //search theo id, mail
    private void searchGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGVActionPerformed
//        SearchStudent ADsearch = new SearchStudent();
//        ADsearch.setVisible(true);
    }//GEN-LAST:event_searchGVActionPerformed

    //click button Exit
    private void btnExitQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitQLSVActionPerformed
        AdminPage ad = new AdminPage();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitQLSVActionPerformed

    //click button delete > delete data in table and file
    private void btnDeleteGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGVActionPerformed
        // TODO add your handling code here:
        try {
            int i = table_GV.getSelectedRow();
            DefaultTableModel tableModel = (DefaultTableModel) table_GV.getModel();
            if (i >= 0) {
                //delete data in table
                String idDel = tableModel.getValueAt(i, 0).toString();
                tableModel.removeRow(i);
                //delete data in arraylist
                for (int j = 0; j < listLecturer.size(); j++) {
                    if (listLecturer.get(i).getId().equals(idDel)) {
                        listLecturer.remove(i);
                        JOptionPane.showMessageDialog(null, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        lecturerApp.saveFile(listLecturer);
                        break;
                    }
                }
            }
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Xóa không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteGVActionPerformed

    //click button Edit > update data in table and file
    private void btnEditQLGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditQLGVActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) table_GV.getModel();
        try {
            int i = table_GV.getSelectedRow();
            //edit table
            tableModel.setValueAt(textId.getText(), i, 0);
            tableModel.setValueAt(textPassword.getText(), i, 1);
            tableModel.setValueAt(textName.getText(), i, 2);
            tableModel.setValueAt(textBirthday.getText(), i, 3);
            tableModel.setValueAt(textAddress.getText(), i, 4);
            tableModel.setValueAt(textEmail.getText(), i, 5);
            tableModel.setValueAt(textPhone.getText(), i, 6);
            tableModel.setValueAt(textLiteracy.getText(), i, 7);
            tableModel.setValueAt(selectSchool.getSelectedItem().toString(), i, 8);

            //edit arraylist
            listLecturer.get(i).setId(textId.getText());
            listLecturer.get(i).setPassword(textPassword.getText());
            listLecturer.get(i).setName(textName.getText());
            listLecturer.get(i).setBirthday(textBirthday.getText());
            listLecturer.get(i).setAddress(textAddress.getText());
            listLecturer.get(i).setEmail(textEmail.getText());
            listLecturer.get(i).setPhone(textPhone.getText());
            listLecturer.get(i).setLiteracy(textLiteracy.getText());
            listLecturer.get(i).setSchool(selectSchool.getSelectedItem().toString());

            lecturerApp.saveFile(listLecturer);
            JOptionPane.showMessageDialog(null, "Thao tác thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Thao tác không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEditQLGVActionPerformed

    //when click to a row, the row's detail info display in Detail Info in the left
    private void table_GVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_GVMouseClicked
        // TODO add your handling code here:
        int index = table_GV.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) table_GV.getModel();
        textId.setText(tableModel.getValueAt(index, 0).toString());
        textPassword.setText(tableModel.getValueAt(index, 1).toString());
        textName.setText(tableModel.getValueAt(index, 2).toString());
        textBirthday.setText(tableModel.getValueAt(index, 3).toString());
        textAddress.setText(tableModel.getValueAt(index, 4).toString());
        textEmail.setText(tableModel.getValueAt(index, 5).toString());
        textPhone.setText(tableModel.getValueAt(index, 6).toString());
        textLiteracy.setText(tableModel.getValueAt(index, 7).toString());
        String schoolSelected = tableModel.getValueAt(index, 8).toString();
        switch (schoolSelected) {
            case "Viện Công nghệ thông tin và truyền thông": {
                selectSchool.setSelectedIndex(0);
            }
            break;
            case "Viện Dệt may": {
                selectSchool.setSelectedIndex(1);
            }
            break;
            case "Viện Cơ khí": {
                selectSchool.setSelectedIndex(2);
            }
            break;
            case "Viện Vật lý kĩ thuật": {
                selectSchool.setSelectedIndex(3);
            }
            break;
            case "Viện Điện": {
                selectSchool.setSelectedIndex(4);
            }
            break;
            case "Viện Điện tử Viễn thông": {
                selectSchool.setSelectedIndex(5);
            }
            break;
            case "Viện Ngoại Ngữ": {
                selectSchool.setSelectedIndex(6);
            }
            break;
            case "Viện Đào tạo Quốc tế": {
                selectSchool.setSelectedIndex(7);
            }
            break;
            case "Viện Kinh tế quản lý": {
                selectSchool.setSelectedIndex(8);
            }
            break;
        }

    }//GEN-LAST:event_table_GVMouseClicked

    //click button add a student
    private void btnAddGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGVActionPerformed

        if (lecturerApp.searchLecturer(textId.getText(), textEmail.getText()) == -3 || lecturerApp.searchLecturer(textId.getText(), textEmail.getText()) == -1) {

            //add to arrayList
            Lecturer lecturer = new Lecturer();
            if (lecturerApp.searchLecturer(textId.getText(), "") == -1) {
                lecturer.setId(textId.getText());
                if (textPassword.getText().isEmpty() || textName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Tên và mật khẩu không được để trông", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    lecturer.setPassword(textPassword.getText());
                    lecturer.setName(textName.getText());
                    if (checkData.checkBirthday(textBirthday.getText())) {
                        lecturer.setBirthday(textBirthday.getText());
                        if (checkData.checkEmail(textEmail.getText())) {
                            lecturer.setEmail(textEmail.getText());
                            if (checkData.checkPhone(textPhone.getText())) {
                                lecturer.setPhone(textPhone.getText());
                                lecturer.setSchool(selectSchool.getSelectedItem().toString());
                                if (textAddress.getText().isEmpty() || textLiteracy.getText().isEmpty()) {
                                    JOptionPane.showMessageDialog(null, "Địa chỉ và trình độ không được để trống", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                                } else {
                                    lecturer.setAddress(textAddress.getText());
                                    lecturer.setLiteracy(textLiteracy.getText());
                                    listLecturer.add(lecturer);
                                    lecturerApp.saveFile(listLecturer);

                                    //add student's info to table 
                                    DefaultTableModel tableModel = (DefaultTableModel) table_GV.getModel();
                                    tableModel.addRow(new Object[]{textId.getText(), textPassword.getText(), textName.getText(), textBirthday.getText(),
                                        textAddress.getText(), textEmail.getText(), textPhone.getText(), textLiteracy.getText(), selectSchool.getSelectedItem()});
                                    JOptionPane.showMessageDialog(null, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                                }
                            }
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "ID is noe available", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "ID or email not available", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnAddGVActionPerformed

    private void textIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIdKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_textIdKeyPressed

    //load data from arrayList to table
    private void showLecturerList(ArrayList<Lecturer> listLecturer) {
        DefaultTableModel model = (DefaultTableModel) table_GV.getModel();
        Object[] row;
        for (int i = 0; i < listLecturer.size(); i++) {
            row = new Object[9];
            row[0] = listLecturer.get(i).getId();
            row[1] = listLecturer.get(i).getPassword();
            row[2] = listLecturer.get(i).getName();
            row[3] = listLecturer.get(i).getBirthday();
            row[4] = listLecturer.get(i).getAddress();
            row[5] = listLecturer.get(i).getEmail();
            row[6] = listLecturer.get(i).getPhone();
            row[8] = listLecturer.get(i).getSchool();
            row[7] = listLecturer.get(i).getLiteracy();
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminQLGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminQLGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminQLGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminQLGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminQLGV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGV;
    private javax.swing.JButton btnDeleteGV;
    private javax.swing.JButton btnEditQLGV;
    private javax.swing.JButton btnExitQLSV;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchGV;
    private javax.swing.JComboBox<String> selectSchool;
    private javax.swing.JTable table_GV;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textBirthday;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textLiteracy;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textPassword;
    private javax.swing.JTextField textPhone;
    // End of variables declaration//GEN-END:variables
}
