/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import App.SVTCApp;
import Object.SVTC;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class AdminQLSVTC extends javax.swing.JFrame {

    /**
     * Creates new form QLSV
     */
    SVTCApp svtcApp = new SVTCApp();
    ArrayList<SVTC> listSVTC = svtcApp.loadFile();

    public AdminQLSVTC() {
        initComponents();
        showStudentList(listSVTC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textBirthday = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textPhone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textPassword = new javax.swing.JTextField();
        selectCourse = new javax.swing.JComboBox<>();
        selectSchool = new javax.swing.JComboBox<>();
        btnEditSVTC = new javax.swing.JButton();
        btnDeleteSVTC = new javax.swing.JButton();
        btnExitQLSVTC = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_SVTC = new javax.swing.JTable();
        btnSearchSVTC = new javax.swing.JButton();
        btnAddSVTC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên tín chỉ");

        jPanel3.setBackground(new java.awt.Color(53, 53, 242));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Mã số SV");

        textId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textIdKeyPressed(evt);
            }
        });

        jLabel2.setText("Họ và tên");

        jLabel3.setText("Ngày sinh");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Địa chỉ email");

        jLabel7.setText("Số điện thoại");

        jLabel8.setText("Viện đào tạo ");

        jLabel9.setText("Khóa học");

        jLabel12.setText("Mật khẩu");

        selectCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "57", "58", "59", "60", "61", "62" }));

        selectSchool.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Viện Công nghệ thông tin và truyền thông", "Viện Dệt may", "Viện Cơ khí", "Viện Vật lý kĩ thuật", "Viện Điện", "Viện Điện tử Viễn thông", "Viện Ngoại Ngữ", "Viện Đào tạo Quốc tế", "Viện Kinh kế và quản lý" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectSchool, 0, 0, Short.MAX_VALUE)
                    .addComponent(textPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textAddress)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textId))
                    .addComponent(textName)
                    .addComponent(textEmail)
                    .addComponent(textPhone)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(selectCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(0, 111, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(4, 4, 4)
                .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(selectSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(82, 82, 82))
        );

        btnEditSVTC.setBackground(new java.awt.Color(35, 35, 253));
        btnEditSVTC.setText("Sửa");
        btnEditSVTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSVTCActionPerformed(evt);
            }
        });

        btnDeleteSVTC.setBackground(new java.awt.Color(35, 35, 253));
        btnDeleteSVTC.setText("Xóa");
        btnDeleteSVTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSVTCActionPerformed(evt);
            }
        });

        btnExitQLSVTC.setBackground(new java.awt.Color(35, 35, 253));
        btnExitQLSVTC.setText("Thoát");
        btnExitQLSVTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitQLSVTCActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH SINH VIÊN TÍN CHỈ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N

        table_SVTC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Mật khẩu", "Họ tên", "Ngày sinh", "Địa chỉ", "Email", "SĐT", "Viện/Khoa", "Khóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_SVTC.setColumnSelectionAllowed(true);
        table_SVTC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_SVTCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_SVTC);
        table_SVTC.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
        );

        btnSearchSVTC.setBackground(new java.awt.Color(35, 35, 253));
        btnSearchSVTC.setText("Tìm kiếm");
        btnSearchSVTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSVTCActionPerformed(evt);
            }
        });

        btnAddSVTC.setBackground(new java.awt.Color(35, 35, 253));
        btnAddSVTC.setText("Thêm");
        btnAddSVTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSVTCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnSearchSVTC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddSVTC)
                .addGap(31, 31, 31)
                .addComponent(btnEditSVTC)
                .addGap(40, 40, 40)
                .addComponent(btnDeleteSVTC)
                .addGap(44, 44, 44)
                .addComponent(btnExitQLSVTC)
                .addGap(283, 283, 283))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(636, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditSVTC)
                    .addComponent(btnDeleteSVTC)
                    .addComponent(btnExitQLSVTC)
                    .addComponent(btnSearchSVTC)
                    .addComponent(btnAddSVTC)))
        );

        btnEditSVTC.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //search student by MSSV and email
    private void btnSearchSVTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSVTCActionPerformed
        SearchStudent ADsearch = new SearchStudent();
        ADsearch.setVisible(true);
    }//GEN-LAST:event_btnSearchSVTCActionPerformed

    //click Exit
    private void btnExitQLSVTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitQLSVTCActionPerformed
        // TODO add your handling code here:
        AdminPage ad = new AdminPage();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitQLSVTCActionPerformed

    //click button delete > delete data in table and file
    private void btnDeleteSVTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSVTCActionPerformed
        try {
            int i = table_SVTC.getSelectedRow();
            DefaultTableModel tableModel = (DefaultTableModel) table_SVTC.getModel();
            if (i >= 0) {
                //delete data in table
                String idDel = tableModel.getValueAt(i, 0).toString();
                tableModel.removeRow(i);
                //delete data in arraylist
                for (int j = 0; j < listSVTC.size(); j++) {
                    if (listSVTC.get(i).getId().equals(idDel)) {
                        listSVTC.remove(i);
                        JOptionPane.showMessageDialog(null, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        svtcApp.saveFile(listSVTC);
                        break;
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Xóa không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnDeleteSVTCActionPerformed

    //click button Edit > update data in table and file
    private void btnEditSVTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSVTCActionPerformed

        try {
            DefaultTableModel tableModel = (DefaultTableModel) table_SVTC.getModel();
            int i = table_SVTC.getSelectedRow();
            //edit table
            tableModel.setValueAt(textId.getText(), i, 0);
            tableModel.setValueAt(textPassword.getText(), i, 1);
            tableModel.setValueAt(textName.getText(), i, 2);
            tableModel.setValueAt(textBirthday.getText(), i, 3);
            tableModel.setValueAt(textAddress.getText(), i, 4);
            tableModel.setValueAt(textEmail.getText(), i, 5);
            tableModel.setValueAt(textPhone.getText(), i, 6);
            tableModel.setValueAt(selectSchool.getSelectedItem().toString(), i, 7);
            tableModel.setValueAt(selectCourse.getSelectedItem().toString(), i, 8);
            //edit arraylist
            listSVTC.get(i).setId(textId.getText());
            listSVTC.get(i).setPassword(textPassword.getText());
            listSVTC.get(i).setName(textName.getText());
            listSVTC.get(i).setBirthday(textBirthday.getText());
            listSVTC.get(i).setAddress(textAddress.getText());
            listSVTC.get(i).setEmail(textEmail.getText());
            listSVTC.get(i).setPhone(textPhone.getText());
            listSVTC.get(i).setSchool(selectSchool.getSelectedItem().toString());
            listSVTC.get(i).setCourse(selectCourse.getSelectedItem().toString());
            svtcApp.saveFile(listSVTC);
            JOptionPane.showMessageDialog(null, "Thao tác thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Thao tác không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEditSVTCActionPerformed

    //đưa thông tin từ bảng dữ liệu ra phần thông tin chi tiết
    private void table_SVTCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_SVTCMouseClicked
        // TODO add your handling code here:
        int index = table_SVTC.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) table_SVTC.getModel();
        textId.setText(tableModel.getValueAt(index, 0).toString());
        textPassword.setText(tableModel.getValueAt(index, 1).toString());
        textName.setText(tableModel.getValueAt(index, 2).toString());
        textBirthday.setText(tableModel.getValueAt(index, 3).toString());
        textAddress.setText(tableModel.getValueAt(index, 4).toString());
        textEmail.setText(tableModel.getValueAt(index, 5).toString());
        textPhone.setText(tableModel.getValueAt(index, 6).toString());
        String schoolSelected = tableModel.getValueAt(index, 7).toString();
        switch (schoolSelected) {
            case "Viện Công nghệ thông tin và truyền thông": {
                selectSchool.setSelectedIndex(0);
            }
            break;
            case "Viện Dệt may": {
                selectSchool.setSelectedIndex(1);
            }
            break;
            case "Viện Cơ khí": {
                selectSchool.setSelectedIndex(2);
            }
            break;
            case "Viện Vật lý kĩ thuật": {
                selectSchool.setSelectedIndex(3);
            }
            break;
            case "Viện Điện": {
                selectSchool.setSelectedIndex(4);
            }
            break;
            case "Viện Điện tử Viễn thông": {
                selectSchool.setSelectedIndex(5);
            }
            break;
            case "Viện Ngoại Ngữ": {
                selectSchool.setSelectedIndex(6);
            }
            break;
            case "Viện Đào tạo Quốc tế": {
                selectSchool.setSelectedIndex(7);
            }
            break;
            case "Viện Kinh tế quản lý": {
                selectSchool.setSelectedIndex(8);
            }
            break;
        }
        String courseSelected = tableModel.getValueAt(index, 8).toString();
        switch (courseSelected) {
            case "57": {
                selectCourse.setSelectedIndex(0);
            }
            break;
            case "58": {
                selectCourse.setSelectedIndex(1);
            }
            break;
            case "59": {
                selectCourse.setSelectedIndex(2);
            }
            break;
            case "60": {
                selectCourse.setSelectedIndex(3);
            }
            break;
            case "61": {
                selectCourse.setSelectedIndex(4);
            }
            break;
            case "62": {
                selectCourse.setSelectedIndex(5);
            }
            break;
        }

    }//GEN-LAST:event_table_SVTCMouseClicked

    //click add a student
    private void btnAddSVTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSVTCActionPerformed
        if (svtcApp.searchStudent(textId.getText(), textEmail.getText()) == -3) {
            //add student's info to table 
            DefaultTableModel tableModel = (DefaultTableModel) table_SVTC.getModel();
            tableModel.addRow(new Object[]{textId.getText(), textPassword.getText(), textName.getText(), textBirthday.getText(),
                textAddress.getText(), textEmail.getText(), textPhone.getText(), selectSchool.getSelectedItem(), selectCourse.getSelectedItem()});
            //add to arrayList
            SVTC svnc = new SVTC();
            svnc.setId(textId.getText());
            svnc.setPassword(textPassword.getText());
            svnc.setName(textName.getText());
            svnc.setBirthday(textBirthday.getText());
            svnc.setAddress(textAddress.getText());
            svnc.setEmail(textEmail.getText());
            svnc.setPhone(textPhone.getText());
            svnc.setSchool(selectSchool.getSelectedItem().toString());
            svnc.setCourse(selectCourse.getSelectedItem().toString());
            listSVTC.add(svnc);
            svtcApp.saveFile(listSVTC);
            JOptionPane.showMessageDialog(null, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "ID or email not available", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddSVTCActionPerformed

    private void textIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIdKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_textIdKeyPressed

    //load data from arrayList to table
    private void showStudentList(ArrayList<SVTC> listSVTC) {
        DefaultTableModel model = (DefaultTableModel) table_SVTC.getModel();
        Object[] row;
        for (int i = 0; i < listSVTC.size(); i++) {
            row = new Object[9];
            row[0] = listSVTC.get(i).getId();
            row[1] = listSVTC.get(i).getPassword();
            row[2] = listSVTC.get(i).getName();
            row[3] = listSVTC.get(i).getBirthday();
            row[4] = listSVTC.get(i).getAddress();
            row[5] = listSVTC.get(i).getEmail();
            row[6] = listSVTC.get(i).getPhone();
            row[7] = listSVTC.get(i).getSchool();
            row[8] = listSVTC.get(i).getCourse();
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminQLSVTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminQLSVTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminQLSVTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminQLSVTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminQLSVTC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSVTC;
    private javax.swing.JButton btnDeleteSVTC;
    private javax.swing.JButton btnEditSVTC;
    private javax.swing.JButton btnExitQLSVTC;
    private javax.swing.JButton btnSearchSVTC;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectCourse;
    private javax.swing.JComboBox<String> selectSchool;
    private javax.swing.JTable table_SVTC;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textBirthday;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textPassword;
    private javax.swing.JTextField textPhone;
    // End of variables declaration//GEN-END:variables
}
