/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import App.QLLHT;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public AdminPage() {
        setTitle("Administation");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnQLSVTC = new javax.swing.JButton();
        btnQLGV = new javax.swing.JButton();
        btnQLHP = new javax.swing.JButton();
        btnQLDSV = new javax.swing.JButton();
        btnHTAD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnQLSVNC = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnQLLH = new javax.swing.JButton();
        btnQLCTDT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(20, 149, 33));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        btnQLSVTC.setBackground(new java.awt.Color(89, 99, 243));
        btnQLSVTC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQLSVTC.setText("Quản lý SVTC");
        btnQLSVTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSVTCActionPerformed(evt);
            }
        });

        btnQLGV.setBackground(new java.awt.Color(89, 99, 243));
        btnQLGV.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQLGV.setText("Quản lý Giảng viên");
        btnQLGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLGVActionPerformed(evt);
            }
        });

        btnQLHP.setBackground(new java.awt.Color(89, 99, 243));
        btnQLHP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQLHP.setText("Quản lý học phần");
        btnQLHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHPActionPerformed(evt);
            }
        });

        btnQLDSV.setBackground(new java.awt.Color(89, 99, 243));
        btnQLDSV.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQLDSV.setText("Quản lý điểm SV");
        btnQLDSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDSVActionPerformed(evt);
            }
        });

        btnHTAD.setBackground(new java.awt.Color(89, 99, 243));
        btnHTAD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHTAD.setText("Hệ thống AD");
        btnHTAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHTADActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        jLabel1.setText("Administation");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN");

        btnQLSVNC.setBackground(new java.awt.Color(89, 99, 243));
        btnQLSVNC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQLSVNC.setText("Quản lý SVNC");
        btnQLSVNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSVNCActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(89, 99, 243));
        btnExit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnQLLH.setBackground(new java.awt.Color(89, 99, 243));
        btnQLLH.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQLLH.setText("Quản lý Lớp HT");
        btnQLLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLLHActionPerformed(evt);
            }
        });

        btnQLCTDT.setBackground(new java.awt.Color(89, 99, 243));
        btnQLCTDT.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQLCTDT.setText("Quản lý CTDT");
        btnQLCTDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLCTDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 85, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQLDSV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQLSVTC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQLSVNC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnQLLH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnQLHP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnQLGV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnHTAD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLCTDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQLDSV, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLHP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLGV, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnQLSVTC, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btnQLLH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHTAD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnQLSVNC, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnQLCTDT, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //click button Quản lý SVTC
    private void btnQLSVTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSVTCActionPerformed
        AdminQLSVTC adminQLSVTC = new AdminQLSVTC();
        adminQLSVTC.setVisible(true);
    }//GEN-LAST:event_btnQLSVTCActionPerformed

    //click button Quản lý điểm SV
    private void btnQLDSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDSVActionPerformed
       AdminQLDSV qldsv=new AdminQLDSV();
       qldsv.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnQLDSVActionPerformed

    private void btnHTADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHTADActionPerformed
        AdminQLAD qlad = new AdminQLAD();
        qlad.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHTADActionPerformed

    //click button Quản lý Học phần
    private void btnQLHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHPActionPerformed
        AdminQLHP adminQLHP = new AdminQLHP();
        adminQLHP.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQLHPActionPerformed

    //click button Quản lý SVNC
    private void btnQLSVNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSVNCActionPerformed
        AdminQLSVNC qlNC = new AdminQLSVNC();
        qlNC.setVisible(true);
    }//GEN-LAST:event_btnQLSVNCActionPerformed

    //click button Quản lý Giảng viên
    private void btnQLGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLGVActionPerformed
        AdminQLGV qlGV= new AdminQLGV();
        qlGV.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQLGVActionPerformed

    //click button exit, back to Login frame
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnQLCTDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLCTDTActionPerformed
        AdminQLCTDT qlCTDT = new AdminQLCTDT();
        qlCTDT.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQLCTDTActionPerformed

    private void btnQLLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLLHActionPerformed
        AdminQLLHT qllh = new AdminQLLHT();
        qllh.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQLLHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHTAD;
    private javax.swing.JButton btnQLCTDT;
    private javax.swing.JButton btnQLDSV;
    private javax.swing.JButton btnQLGV;
    private javax.swing.JButton btnQLHP;
    private javax.swing.JButton btnQLLH;
    private javax.swing.JButton btnQLSVNC;
    private javax.swing.JButton btnQLSVTC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
